import { useState } from 'react'
import { motion, useReducedMotion } from 'framer-motion'
const pixels=['11100111','10000001','00011000','10000001','11100111','11100111','11100111','11011011']
export function LessonDemo({type}:{type:string}) {
 const [step,setStep]=useState(0); const [value,setValue]=useState(345); const [a,setA]=useState(true);const [b,setB]=useState(false); const reduce=useReducedMotion()
 if(type==='binary') {
  let n=value;const rows=[]; do {rows.push([n,Math.floor(n/2),n%2]);n=Math.floor(n/2)}while(n>0)
  return <><div className="demo-label">BINARY LAB</div><label className="demo-input">Decimal number<input type="number" min="0" max="65535" value={value} onChange={e=>{setValue(Math.max(0,Math.min(65535,Math.trunc(Number(e.target.value)))));setStep(0)}}/></label><div className="division-table"><div>Divide by 2</div><div>Quotient</div><div>Remainder</div>{rows.slice(0,step+1).map(([n,q,r],i)=><motion.div className="division-row" key={i} initial={{opacity:0}} animate={{opacity:1}}><span>{n} ÷ 2</span><span>{q}</span><strong>{r}</strong></motion.div>)}</div><button className="reveal-button" disabled={step>=rows.length-1} onClick={()=>setStep(step+1)}>Next division</button>{step>=rows.length-1 && <div className="big-result">{value.toString(2)}<sub>2</sub><p>Read remainders from bottom to top.</p></div>}</>
 }
 if(type==='pixels') return <><div className="demo-label">A PICTURE MADE OF BITS</div><div className="pixel-grid">{pixels.join('').split('').map((bit,i)=><motion.div key={i} initial={{opacity:reduce?1:0}} animate={{opacity:1}} transition={{delay:reduce?0:i*.01}} style={{background:bit==='0'?'#10251a':'#fff',color:bit==='0'?'#fff':'#10251a'}}>{a?bit:''}</motion.div>)}</div><button className="reveal-button" onClick={()=>setA(!a)}>{a?'Hide bits':'Show bits'}</button><p className="demo-caption">Chapter convention: black = 0, white = 1.<br/>8 × 8 pixels = 64 bits for the pixel values.</p></>
 if(type==='trace') {const states=[['—','—','—'],['5','—','—'],['5','10','—'],['5','10','5'],['5','5','5']];const lines=['Ready to run','x ← 5','y ← 10','z ← x','y ← z'];return <><div className="demo-label">VARIABLE MEMORY</div><div className="memory-grid">{['x','y','z'].map((name,i)=><div key={name}><span>{name}</span><motion.strong key={states[step][i]} initial={{scale:reduce?1:.8}} animate={{scale:1}}>{states[step][i]}</motion.strong></div>)}</div><div className="trace-line">{lines[step]}</div><button className="reveal-button" onClick={()=>setStep((step+1)%5)}>{step===4?'Restart trace':'Run next line'}</button><p className="demo-caption">Assignment copies the current value. It does not permanently link two variables.</p></>}
 if(type==='order') {const steps=['2 + 3 × 4²','2 + 3 × 16','2 + 48','50'];return <><div className="demo-label">ORDER OF OPERATIONS</div><div className="expression">{steps[step]}</div><div className="step-chips">{['Expression','Exponent','Multiply','Add'].map((s,i)=><span className={i===step?'active':''} key={s}>{s}</span>)}</div><button className="reveal-button" onClick={()=>setStep((step+1)%4)}>{step===3?'Restart':'Next step'}</button><p className="demo-caption">Multiplication and division share a level; addition and subtraction share a level. Work left to right within each level.</p></>}
 if(type==='index') {const word='PROGRAM';return <><div className="demo-label">STRING INDEX EXPLORER</div><div className="index-grid">{word.split('').map((c,i)=><button key={i} className={step===i?'active':''} onClick={()=>setStep(i)}><small>{i}</small><strong>{c}</strong></button>)}</div><div className="big-result">word[{step}] → "{word[step]}"</div><p className="demo-caption">JavaScript starts at index 0.<br/>word.substring(0, 4) → "PROG"<br/>The end index is excluded.</p></>}
 return <><div className="demo-label">BOOLEAN PLAYGROUND</div><div className="logic-switches"><button onClick={()=>setA(!a)}>P: <strong>{String(a)}</strong></button><button onClick={()=>setB(!b)}>Q: <strong>{String(b)}</strong></button></div><div className="logic-results">{[['P AND Q',a&&b],['P OR Q',a||b],['NOT P',!a],['NOT (P OR Q)',!(a||b)],['(NOT P) AND (NOT Q)',!a&&!b]].map(([label,result])=><div key={String(label)}><span>{label}</span><strong className={result?'truth':'falsehood'}>{String(result)}</strong></div>)}</div><p className="demo-caption">Toggle P and Q. The last two expressions always agree: De Morgan’s second law.</p></>
}
